name: PollApp CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simple Log Message
        run: echo "CI Pipeline Triggered Successfully!"