name: PollApp CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: AI Code Review
        uses: AleksandrFurmenkovOfficial/ai-code-review@v0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          ai_provider: 'google'
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          google_model: 'gemini-2.5-flash'
  run-tests:
    runs-on: ubuntu-latest
    needs: ai-code-review # This job runs only after the code review job succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test