name: PollApp CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: AI Code Review
        uses: AleksandrFurmenkovOfficial/ai-code-review@v0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          ai_provider: 'google'
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          google_model: 'gemini-2.5-flash'